name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Set up Ruby
    environment: CI
    strategy:
      matrix:
        ruby:
          - '3.2.5'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

  test:
    runs-on: ubuntu-latest
    name: RSpec Tests
    environment: CI
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.5'
          bundler-cache: true
      - name: Run RSpec tests
        run: bundle exec rake
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./coverage/coverage.xml
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  lint:
    runs-on: ubuntu-latest
    name: Rubocop Scan
    environment: CI
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.5'
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop
