name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    environment: CI
    strategy:
      matrix:
        ruby:
          - '3.2.5'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: RSpec tests
      run: bundle exec rake
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        files: ./coverage/coverage.xml
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
    - name: Rubocop Scan
      run: bundle exec rubocop